version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - 'mysql-data:/var/lib/mysql'
    ports:
      - 4307:5432

volumes:
  mysql-data:
