# version: '3.8'
# services:
#   db:
#     image: postgres:14
#     environment:
#       POSTGRES_PASSWORD: password
#       POSTGRES_USER: postgres
#     volumes:
#       - 'mysql-data:/var/lib/mysql'
#     ports:
#       - 4307:5432

# volumes:
#   mysql-data:

version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 8080:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 4307:5432

volumes:
  postgres:
    name: nest-prisma-docker-db
